### ISSUE TITLE
``aio threads`` unsupported on macOS

### ISSUE THREAD

**Issue by mpasternak** [lahwaacz/pytest-nginx#1]
Hi, 

thanks for a useful package, 

when starting with default configuration template on macOS, nginx is unable to start because of:
```
nginx: [emerg] "aio threads" is unsupported on this platform in /private/var/folders/6j/58hrtnm147b7xg7h813ds0080000gn/T/pytest-of-mpast
```

There are a few solutions IMO...

1. remove "aio threads" from default template

2. use different template for macOS

I can prepare a pull request, any suggestions which way should I go?

**Comment by lahwaacz** [comment]
You can use `nginx_config_template`/`--nginx-config-template` to supply an alternative template, see the [configuration](https://github.com/lahwaacz/pytest-nginx#configuration) section. I can't test on macOS so it's best to consider it as an unsupported platform.

**Comment by mpasternak** [comment]
I have 2 improvement which should I present to you shortly in a form of PR. Thanks.
